"""Blog / guide articles – long-form SEO content targeting informational searches."""

POSTS = [
    {
        "slug": "printed-packaging-cost-sri-lanka",
        "title": "How Much Does Printed Packaging Cost in Sri Lanka? (2026 Price Guide)",
        "seo_title": "Printed Packaging Cost in Sri Lanka: 2026 Price Guide",
        "meta": "What printed boxes, labels and cartons cost in Sri Lanka, what drives the price, and nine ways to cut your packaging bill without cutting quality.",
        "date": "2026-09-10",
        "read": "7 min read",
        "category": "Packaging",
        "summary": "What really drives the cost of a printed box or label in Sri Lanka, realistic price ranges, and how to bring the number down.",
        "body": [
            {"h2": "The short answer", "p": "For a standard folding carton printed in four colours on 300 gsm board, most Sri Lankan brands pay somewhere between LKR 25 and LKR 120 per box depending on size, quantity and finish. Labels range from LKR 2 to LKR 20 each. Corrugated mailer boxes typically cost LKR 90 to LKR 350. Those ranges are wide because five factors dominate the price, and you control most of them."},
            {"h2": "1. Quantity is the biggest lever", "p": "Print has high fixed costs (plates, make-ready, cutting die) and low running costs. A 500-piece order might cost LKR 90 per box, while 5,000 of the same box could be LKR 35. Ask your printer for a price at three quantities so you can see the curve and choose the sweet spot for your cash flow."},
            {"h2": "2. Board and material", "p": "Folding box board (FBB) at 300 gsm is the workhorse. Moving to 350–400 gsm adds rigidity and cost; moving to duplex board saves money for inner packaging that nobody sees. For labels, paper is cheapest and PP or PET synthetic materials cost more but survive water and oil."},
            {"h2": "3. Size and sheet utilisation", "p": "Boxes are cut from a standard sheet, so a dieline that fits 12 boxes per sheet is far cheaper than one that fits 9. A few millimetres can change the count. Ask your printer to optimise the box size before you finalise the product label."},
            {"h2": "4. Colours and finishing", "p": "Four-colour process (CMYK) is standard. Each Pantone spot colour adds a plate. Lamination, spot UV, foil and embossing each add a pass through a machine and a setup cost, so on small runs they can double the price; on large runs they add only a few rupees per unit."},
            {"h2": "5. Tooling and samples", "p": "A cutting die costs a one-off LKR 8,000–40,000 depending on size and complexity. Keep the same dieline for reorders and the tooling is free the second time. Physical samples are usually free or credited against the order."},
            {"h2": "Nine ways to reduce packaging cost", "bullets": [
                "Order the annual quantity in two or three drops instead of monthly small runs",
                "Standardise box sizes across SKUs so one die serves many products",
                "Use CMYK plus one spot colour rather than three spot colours",
                "Print inside the box in one colour instead of full colour",
                "Choose a matt aqueous coating instead of lamination where scuff resistance is not critical",
                "Reduce board weight by 50 gsm if a crash-lock base gives the strength you need",
                "Ask about house stock papers that the printer buys in volume",
                "Approve artwork once and reorder from archived files",
                "Use digital printing for launches under 500 units, then switch to offset",
            ]},
            {"h2": "Get an exact number", "p": "The fastest way to know is to send us product dimensions, quantity and a reference of the look you want. We reply within one working day with a costed proposal at three quantities and a free dieline, or use our instant estimate tool on the quote page."},
        ],
        "cta": "quote",
    },
    {
        "slug": "print-ready-artwork-checklist",
        "title": "Print-Ready Artwork Checklist: 12 Things to Check Before You Send Files to Your Printer",
        "seo_title": "Print-Ready Artwork Checklist: 12 Checks Before Press",
        "meta": "The 12-point print-ready checklist our prepress team runs on every file: bleed, resolution, CMYK, fonts, dielines, overprint and barcodes. Free PDF.",
        "date": "2026-08-22",
        "read": "6 min read",
        "category": "Prepress",
        "summary": "The exact checklist our prepress team runs on every file, so your job goes to press first time.",
        "body": [
            {"h2": "Why files get rejected", "p": "Nine out of ten delays in a print job happen before the press starts: a missing font, an RGB image, a logo at 72 dpi, a box artwork built on the wrong dieline. Fixing them costs a day each. This checklist prevents all of them."},
            {"h2": "The 12-point checklist", "bullets": [
                "Bleed: extend background colour and images 3 mm beyond the trim line on every side",
                "Safe zone: keep text and logos at least 3–5 mm inside the trim line",
                "Resolution: images at 300 dpi at final size (150 dpi is acceptable for large format)",
                "Colour mode: CMYK for process colour; specify Pantone names for spot colours; never RGB",
                "Rich black: use C60 M40 Y40 K100 for large black areas, plain K100 for small text",
                "Fonts: outline all text or package fonts with the file; minimum 6 pt for body text, 4 pt for legal",
                "Dieline: place artwork on the printer's dieline on a separate, non-printing spot-colour layer",
                "Overprint: check overprint preview; white text set to overprint disappears",
                "Barcodes: minimum 80% magnification, quiet zones, dark on light background, verified",
                "Transparency and effects: flatten or export as PDF/X-4 to avoid rendering surprises",
                "Page setup: single pages in reading order, correct trim size, no printer's marks in the artwork area",
                "Export: PDF/X-4 or PDF/X-1a with crop marks and 3 mm bleed, fonts embedded",
            ]},
            {"h2": "Packaging-specific checks", "p": "For boxes and labels, also check that the glue flap is free of ink (unless the printer confirms glueable varnish), that artwork on adjacent panels reads correctly when folded, and that any window matches the die. A folded paper mock-up from your desktop printer catches most orientation mistakes."},
            {"h2": "What we do on our side", "p": "Every job receives a free preflight. We report issues with a marked-up PDF, fix minor problems without charge, and send a soft proof or a physical proof before anything is printed."},
            {"h2": "Download the checklist", "p": "Keep the checklist next to your designer. Download the one-page PDF from our resources page."},
        ],
        "cta": "resources",
    },
    {
        "slug": "choose-box-style-for-your-product",
        "title": "How to Choose the Right Box Style for Your Product: Folding Carton, Rigid Box or Corrugated Mailer?",
        "seo_title": "Folding Carton vs Rigid Box vs Mailer: Which to Choose",
        "meta": "Compare folding cartons, rigid boxes and corrugated mailers on cost, protection, minimums and shelf appeal, with recommendations by product type.",
        "date": "2026-07-30",
        "read": "8 min read",
        "category": "Packaging",
        "summary": "A decision guide comparing the three main box families on cost, protection, minimums and brand impact.",
        "body": [
            {"h2": "Three families of boxes", "p": "Almost every printed box belongs to one of three families. Folding cartons are die-cut from a single sheet of board and shipped flat. Rigid boxes are built from thick greyboard wrapped in printed paper and shipped assembled. Corrugated boxes use fluted board for strength and are the choice for shipping. Each has a sweet spot."},
            {"h2": "Folding cartons", "p": "Best for retail products under about 2 kg that sit on a shelf: cosmetics, tea, pharmaceuticals, food, small electronics. Lowest unit cost at volume, fastest to produce, fully printable with premium finishes. Minimums from 500 on offset or 50 on digital. Weakness: limited protection in transit, so they are usually packed inside a corrugated shipper."},
            {"h2": "Rigid boxes", "p": "Best when the box itself is part of the product: jewellery, premium tea, gift sets, luxury cosmetics, corporate gifts, phones. Highest perceived value and structural strength, with inserts that hold products in place. Minimums from 100. Weakness: higher unit cost and bulky shipping unless you choose a collapsible design."},
            {"h2": "Corrugated boxes", "p": "Best for anything that ships: e-commerce orders, export cartons, subscription boxes, food delivery. Strong, light, low cost per unit of protection. Die-cut mailers can be fully printed for an unboxing experience. Weakness: print quality on flute is lower than on board unless litho-laminated."},
            {"h2": "Quick comparison", "table": {
                "head": ["Factor", "Folding carton", "Rigid box", "Corrugated mailer"],
                "rows": [
                    ["Unit cost", "Low", "High", "Low–medium"],
                    ["Protection", "Light", "High", "High"],
                    ["Print quality", "Excellent", "Excellent (wrap)", "Good (flexo) / excellent (litho-lam)"],
                    ["Minimum order", "50–500", "100", "100–500"],
                    ["Ships flat?", "Yes", "Usually no", "Yes"],
                    ["Best for", "Retail shelf", "Gifting & luxury", "Shipping & e-commerce"],
                ]}},
            {"h2": "Recommendations by product", "bullets": [
                "Tea (retail 100–250 g): folding carton, add a rigid box or tube for gift grades",
                "Skincare and cosmetics: folding carton with foil or soft-touch; rigid box for sets",
                "Chocolates and confectionery: folding carton with insert, rigid box for premium",
                "Apparel e-commerce: corrugated mailer with inside print and tissue",
                "Spices and dry foods for export: folding carton inside a printed RSC shipper",
                "Jewellery and gems: rigid box with foam or velvet insert",
                "Bakery: E-flute or FBB cake boxes with window",
            ]},
            {"h2": "Still unsure?", "p": "Send us the product and we will propose two or three structures with white samples and pricing at your quantity, free of charge."},
        ],
        "cta": "quote",
    },
    {
        "slug": "tea-packaging-design-guide-sri-lanka",
        "title": "Tea Packaging Design Guide for Ceylon Tea Exporters: Structures, Materials and Compliance",
        "seo_title": "Tea Packaging Design Guide for Ceylon Tea Exporters",
        "meta": "Carton structures, barrier materials, tea bag envelopes, gift boxes, Lion logo rules, food-contact compliance and export carton specs for Ceylon tea.",
        "date": "2026-07-05",
        "read": "9 min read",
        "category": "Industry guides",
        "summary": "Everything a tea brand needs to know about cartons, envelopes, gift boxes, barrier materials and export compliance.",
        "body": [
            {"h2": "Why packaging decides the price of tea", "p": "Two teas from the same estate can retail at three times the price difference, and packaging accounts for most of that gap. Importers and retailers buy on shelf presence, perceived quality and compliance. This guide covers the packaging formats that Ceylon tea exporters use and what to consider for each."},
            {"h2": "Retail carton formats", "bullets": [
                "Tuck-end cartons for 100–250 g loose tea, usually with an inner foil or metallised pouch",
                "Tea bag cartons for 20–100 bags, with or without individual envelopes",
                "Crash-lock cartons for heavier 400–500 g packs",
                "Display cartons with a tear-off front for cash-and-carry markets",
                "Window cartons showing pyramid bags through PET or PLA film",
            ]},
            {"h2": "Barrier and freshness", "p": "Tea absorbs moisture and odours. A carton alone is not a barrier, so brands use an inner foil pouch, a metallised film sachet or a lined carton. For premium loose tea, a tin or a rigid box with a foil bag inside gives the best shelf life and gift value."},
            {"h2": "Tea bag envelopes", "p": "Individually enveloped tea bags command higher prices in hotel and export channels. Envelopes are printed on heat-sealable paper or paper/foil laminates and can be digitally printed so a range of ten flavours can be produced economically."},
            {"h2": "Gift and premium packaging", "p": "Rigid boxes, drawer boxes, round tubes and wooden-look boxes with foil, embossing and satin inserts serve the gifting market during Ramadan, Christmas, Chinese New Year and tourist seasons. Collapsible rigid boxes reduce freight cost for export."},
            {"h2": "Compliance essentials", "bullets": [
                "Sri Lanka Tea Board Lion logo: only on 100% pure Ceylon tea packed in Sri Lanka, per Tea Board guidelines",
                "Food-contact: virgin board and low-migration inks with a declaration of compliance for EU/UK importers",
                "Mandatory information: product name, net weight, ingredients, origin, best-before, lot code, importer address, nutrition where required",
                "Barcodes: GS1 EAN-13 on retail units, ITF-14 on shipping cartons",
                "Language: many markets require local-language labelling; plan panel space early",
            ]},
            {"h2": "Export shipping cartons", "p": "Master cartons should be specified by board grade (for example 5-ply BC flute, 150/120/150 gsm liners), tested for edge crush, and printed with brand, product, quantity, lot, weight and handling marks. Pallet pattern planning avoids overhang and crushed corners."},
            {"h2": "How we help tea exporters", "p": "We supply cartons, envelopes, labels, rigid gift boxes and shipping cartons from one facility in Colombo, with free dielines and food-contact documentation. See our tea packaging page or request samples."},
        ],
        "cta": "industry:tea-exporters",
    },
]

POST_BY_SLUG = {p["slug"]: p for p in POSTS}
