"""Industry landing pages – each becomes /industries/<slug>/ (targets 'packaging for X in Sri Lanka' searches)."""

INDUSTRIES = [
    {
        "slug": "tea-exporters",
        "name": "Tea Exporters & Tea Brands",
        "short": "Tea cartons, tea bag envelopes, tins labels and gift boxes for Ceylon tea.",
        "icon": "tea",
        "title": "Tea Packaging for Ceylon Tea Exporters | Sri Lanka",
        "meta": "Printed tea cartons, tea bag envelopes, tin labels, rigid gift boxes and export shipping cartons for Ceylon tea exporters. Food-safe, made in Colombo.",
        "h1": "Packaging for Ceylon Tea Exporters",
        "intro": "Ceylon tea competes on the shelf in Dubai, Moscow, Tokyo and Berlin. We produce the retail cartons, envelopes, tins labels, gift boxes and shipping cartons that carry the Lion logo with the quality it deserves, from Colombo, close to your blending and packing facility.",
        "pains": [
            "Buyers abroad demand consistent colour and structure across every reorder",
            "Seasonal gift-pack deadlines for Ramadan, Christmas and Chinese New Year",
            "Food-contact compliance and material declarations for EU and Gulf importers",
            "Many SKUs (grades, flavours, languages) with modest quantities each",
        ],
        "solutions": [
            ("Printed tea cartons", "Tuck-end and crash-lock folding cartons for 25 g to 500 g packs, with inner foil or pouch options.", "packaging-boxes"),
            ("Tea bag envelopes & sachets", "Heat-sealable printed envelopes and string-and-tag outers, digitally printed for multi-flavour ranges.", "labels-stickers"),
            ("Rigid gift boxes & tubes", "Magnetic boxes, drawer boxes and round tubes with foil, embossing and fitted inserts for premium ranges.", "rigid-gift-boxes"),
            ("Tin & caddy labels", "Waterproof PP labels and shrink sleeves for tins, caddies and glass jars.", "labels-stickers"),
            ("Export shipping cartons", "ECT-tested corrugated master cartons printed with your brand and buyer codes.", "corrugated-boxes"),
            ("Design & compliance", "Multi-language artwork, nutrition and origin marks, barcode verification, Sri Lanka Tea Board Lion logo placement.", "design-prepress"),
        ],
        "faqs": [
            ("Can you supply packaging that meets EU food-contact rules?", "Yes. We use virgin food-safe board and low-migration inks and provide a declaration of compliance for your importer."),
            ("Do you handle small runs for private-label tea?", "Yes. Digital printing lets us produce from 100 cartons per design, which suits private-label and sample ranges."),
            ("Can you deliver to bonded warehouses or the port?", "Yes. We deliver to your packing facility, bonded warehouse or freight forwarder in Colombo and Katunayake."),
        ],
        "related_services": ["packaging-boxes", "rigid-gift-boxes", "labels-stickers", "corrugated-boxes"],
    },
    {
        "slug": "apparel-garment",
        "name": "Apparel & Garment Exporters",
        "short": "Hang tags, labels, poly bags, shipping cartons and retail packaging for apparel.",
        "icon": "apparel",
        "title": "Apparel Packaging & Hang Tags for Garment Exporters",
        "meta": "Hang tags, swing tickets, size stickers, retail boxes and buyer-spec export cartons for Sri Lankan apparel factories. Delivered daily to BOI zones.",
        "h1": "Packaging & Print for Apparel Exporters",
        "intro": "Sri Lanka's apparel factories ship to the world's most demanding brands, and every shipment carries print: hang tags, care labels, size stickers, polybag inserts, retail boxes and buyer-specified cartons. We produce all of it to spec, on the factory's timeline.",
        "pains": [
            "Buyer tech packs specify exact tag stock, Pantone, barcodes and carton markings",
            "Style changeovers mean many small print runs with zero tolerance for delay",
            "Vendor compliance audits require material and process documentation",
            "Freight cost pressure demands right-sized, right-strength cartons",
        ],
        "solutions": [
            ("Hang tags & swing tickets", "Board tags with foil, embossing, eyelets and strings, printed to buyer artwork with variable barcodes.", "labels-stickers"),
            ("Size & barcode stickers", "Roll labels for polybags and cartons with variable SKU data.", "labels-stickers"),
            ("Retail & gift boxes", "Folding cartons and rigid boxes for lingerie, shirts and premium lines.", "packaging-boxes"),
            ("Export shipping cartons", "Buyer-marked RSC cartons in tested board grades, printed with carton markings and shipping marks.", "corrugated-boxes"),
            ("Factory stationery", "Job cards, cut tickets, inspection forms and NCR books.", "business-stationery"),
            ("Branding for own labels", "Lookbooks, catalogues and store signage for local fashion brands.", "brochures-catalogues"),
        ],
        "faqs": [
            ("Can you match a buyer's tag specification exactly?", "Yes. Send the tech pack and a physical reference tag and we match stock, colour, finish and size, then submit a sample for buyer approval."),
            ("Do you deliver to BOI zones?", "Yes. We deliver daily to Katunayake, Biyagama, Seethawaka, Koggala and Horana zones."),
        ],
        "related_services": ["labels-stickers", "corrugated-boxes", "packaging-boxes", "business-stationery"],
    },
    {
        "slug": "food-beverage",
        "name": "Food, Beverage & FMCG",
        "short": "Folding cartons, labels, sleeves and displays for food and consumer brands.",
        "icon": "food",
        "title": "Food & FMCG Packaging Printing in Sri Lanka",
        "meta": "Printed cartons, roll labels, shrink sleeves, POS displays and shipping cartons for food, beverage and FMCG brands in Sri Lanka. Food-safe materials.",
        "h1": "Packaging for Food, Beverage & FMCG Brands",
        "intro": "From spice exporters and biscuit factories to coconut products, juices and snacks, we supply the primary cartons, labels and secondary packaging that Sri Lankan food brands need to win shelf space at home and abroad.",
        "pains": [
            "Shelf impact at supermarkets like Cargills, Keells and Arpico is decided in seconds",
            "SLS, nutrition, halal and export labelling must be correct on every SKU",
            "Seasonal promotions require quick artwork changes and short runs",
            "Distributors need sturdy shipper cartons and eye-catching displays",
        ],
        "solutions": [
            ("Folding cartons", "Biscuit, tea, spice, cereal and confectionery cartons with window options and food-grade board.", "packaging-boxes"),
            ("Roll labels & shrink sleeves", "Waterproof labels for bottles, jars and pouches, plus full-body shrink sleeves.", "labels-stickers"),
            ("Point-of-sale displays", "Counter units, floor standees, shelf talkers and danglers for promotions.", "brochures-catalogues"),
            ("Shipping cartons", "Printed corrugated shippers and litho-laminated retail-ready trays.", "corrugated-boxes"),
            ("Takeaway packaging", "Cups, sleeves, boxes and bags for food-service brands.", "food-packaging"),
        ],
        "faqs": [
            ("Do you print nutrition panels and SLS marks correctly?", "Yes. Our prepress team checks mandatory labelling elements against the Food Act regulations and your export market requirements before print."),
            ("Can you support a promotion with a two-week deadline?", "Yes. Digital printing and in-house finishing let us turn short-run promotional cartons and labels around in 3–5 days."),
        ],
        "related_services": ["packaging-boxes", "labels-stickers", "food-packaging", "corrugated-boxes"],
    },
    {
        "slug": "pharmaceutical-healthcare",
        "name": "Pharmaceutical & Healthcare",
        "short": "Pharma cartons, leaflets, labels and hospital forms with controlled quality.",
        "icon": "pharma",
        "title": "Pharma Packaging & Hospital Printing, Sri Lanka",
        "meta": "Pharma cartons with braille, patient leaflets, batch-coded labels and hospital forms for Sri Lankan manufacturers, hospitals and labs. Controlled production.",
        "h1": "Pharmaceutical & Healthcare Print and Packaging",
        "intro": "Medicines, supplements, medical devices and hospitals need print that is accurate, traceable and consistent. We serve pharmaceutical manufacturers, importers, ayurvedic producers, hospital chains and laboratories with controlled production and documented quality.",
        "pains": [
            "NMRA-approved artwork must be reproduced exactly, including tiny leaflet text",
            "Batch and expiry variable data on labels and cartons",
            "Mixing of jobs is not acceptable; line clearance and counting are essential",
            "Hospitals need forms, patient leaflets and signage in three languages",
        ],
        "solutions": [
            ("Pharma folding cartons", "Tuck-end cartons with braille embossing, tamper-evident features and lot coding areas.", "packaging-boxes"),
            ("Patient information leaflets", "Miniature-fold leaflets on 40–60 gsm paper with legible small text.", "offset-printing"),
            ("Labels", "Bottle, vial and blister labels with variable batch and expiry data.", "labels-stickers"),
            ("Hospital forms & stationery", "Prescription pads, admission forms, NCR lab request forms, report covers, ID cards.", "business-stationery"),
            ("Patient education & signage", "Trilingual leaflets, posters, wayfinding and department signage.", "large-format-signage"),
        ],
        "faqs": [
            ("Do you have controls to prevent mixed or wrong print?", "Yes. Each pharma job has a single job ticket, line clearance between jobs, 100% count and a retained sample, with a certificate of analysis on request."),
            ("Can you emboss braille on cartons?", "Yes. Braille embossing per Marburg medium standard is available on folding cartons."),
        ],
        "related_services": ["packaging-boxes", "labels-stickers", "business-stationery", "offset-printing"],
    },
    {
        "slug": "cosmetics-ayurveda",
        "name": "Cosmetics, Ayurveda & Wellness",
        "short": "Unit cartons, labels, leaflets and gift sets for beauty and herbal brands.",
        "icon": "cosmetics",
        "title": "Cosmetics & Ayurveda Packaging in Sri Lanka",
        "meta": "Premium unit cartons, waterproof labels, gift sets and leaflets for cosmetics, skincare and ayurveda brands in Sri Lanka. Small runs from 50 pieces.",
        "h1": "Packaging for Cosmetics, Ayurveda & Wellness Brands",
        "intro": "Sri Lankan beauty and ayurvedic brands are winning customers at home and in export markets on the strength of natural ingredients and beautiful packaging. We produce the cartons, labels and gift sets that make a product feel as good as it works.",
        "pains": [
            "Premium look on a start-up budget and small first runs",
            "Labels that survive oils, water and humid bathrooms",
            "Many variants (scents, sizes) with frequent new launches",
            "Ingredient lists and regulatory text in small print",
        ],
        "solutions": [
            ("Unit cartons", "Foil, soft-touch and embossed folding cartons for creams, oils, soaps and serums.", "packaging-boxes"),
            ("Waterproof labels", "PP and PET labels with oil-resistant lamination for bottles, jars and tubes.", "labels-stickers"),
            ("Gift sets & rigid boxes", "Magnetic boxes and trays with inserts for gift ranges and hotel amenity kits.", "rigid-gift-boxes"),
            ("Leaflets & inserts", "Ingredient, usage and brand story inserts printed on textured stocks.", "digital-printing"),
            ("Launch design", "Structural and artwork design that scales from 100 units to 100,000.", "design-prepress"),
        ],
        "faqs": [
            ("What is the minimum order for cosmetic boxes?", "From 50 pieces per design on digital print, which lets you launch a range with modest inventory."),
            ("Can you help with export-market label requirements?", "Yes. We adapt artwork to include ingredient lists (INCI), batch codes, country of origin and importer details for your target markets."),
        ],
        "related_services": ["packaging-boxes", "labels-stickers", "rigid-gift-boxes", "design-prepress"],
    },
    {
        "slug": "hotels-hospitality",
        "name": "Hotels, Restaurants & Tourism",
        "short": "Menus, brochures, amenity packaging, key-card sleeves and takeaway packaging.",
        "icon": "hotel",
        "title": "Hotel & Restaurant Printing in Sri Lanka",
        "meta": "Menus, brochures, key-card sleeves, amenity boxes, paper bags, cake boxes and signage for hotels, resorts and restaurants across Sri Lanka.",
        "h1": "Print & Packaging for Hotels, Restaurants & Tourism",
        "intro": "Every guest touchpoint is a print touchpoint. We supply hotels, resorts, boutique villas, restaurant groups and tour operators with the menus, collateral, amenity packaging, signage and takeaway packaging that make a stay feel considered.",
        "pains": [
            "Frequent menu and price changes need short runs and fast reprints",
            "Guest-facing print must feel premium and match the property's brand",
            "Multiple outlets and properties need consistent standards",
            "Takeaway and delivery packaging must protect food and brand",
        ],
        "solutions": [
            ("Menus & table print", "Laminated, leather-look or synthetic menus, table talkers, tent cards and coasters.", "digital-printing"),
            ("Brochures & guest directories", "Property brochures, in-room compendiums, excursion guides and maps.", "brochures-catalogues"),
            ("Amenity & gift packaging", "Amenity boxes, tea and spice gift packs, welcome-gift rigid boxes.", "rigid-gift-boxes"),
            ("Takeaway packaging", "Cake boxes, meal boxes, cups, sleeves and paper bags with your logo.", "food-packaging"),
            ("Signage & events", "Wayfinding, banquet backdrops, event banners and standees.", "large-format-signage"),
            ("Stationery", "Key-card sleeves, notepads, letterheads, invoice books and name badges.", "business-stationery"),
        ],
        "faqs": [
            ("Can you reprint menus quickly when prices change?", "Yes. We hold your templates and reprint digitally in 24–48 hours."),
            ("Do you supply resorts outside Colombo?", "Yes. We deliver to the south coast, hill country and east coast on scheduled routes."),
        ],
        "related_services": ["digital-printing", "brochures-catalogues", "food-packaging", "large-format-signage"],
    },
    {
        "slug": "ecommerce-retail",
        "name": "E-commerce, Retail & D2C Brands",
        "short": "Mailer boxes, paper bags, stickers, inserts and in-store print for retailers.",
        "icon": "cart",
        "title": "E-commerce & Retail Packaging in Sri Lanka",
        "meta": "Branded mailer boxes, printed paper bags, stickers, tissue and thank-you cards for online sellers and retail chains in Sri Lanka. Low minimums.",
        "h1": "Packaging for E-commerce, Retail & D2C Brands",
        "intro": "Whether you sell on Daraz, Instagram or from a store in Colombo, packaging is your most tangible marketing. We help online sellers, retail chains and direct-to-consumer brands turn every parcel and every bag into a brand experience, with minimums that suit growing businesses.",
        "pains": [
            "Unboxing experience drives repeat purchase and social sharing",
            "Small brands need low minimums and fast reorders",
            "Retail chains need consistent bags, signage and promo print across outlets",
            "Damaged deliveries cost money and reviews",
        ],
        "solutions": [
            ("Mailer boxes", "Die-cut corrugated mailers with inside printing, from 100 pieces.", "corrugated-boxes"),
            ("Paper bags", "Kraft and laminated bags with handles for stores and deliveries.", "paper-bags"),
            ("Stickers, tape & tissue", "Branded stickers, printed packing tape and custom tissue paper.", "labels-stickers"),
            ("Thank-you cards & inserts", "Cards, discount vouchers and care instructions printed digitally.", "digital-printing"),
            ("In-store print", "Shelf talkers, posters, window graphics and promotional standees.", "large-format-signage"),
        ],
        "faqs": [
            ("What is the cheapest way to brand my parcels?", "Start with a branded sticker and tissue paper on a plain mailer, then upgrade to a printed mailer box as volume grows."),
            ("Can I order 100 mailer boxes?", "Yes. Die-cut mailers start from 100 pieces and we hold the die for cheap reorders."),
        ],
        "related_services": ["corrugated-boxes", "paper-bags", "labels-stickers", "digital-printing"],
    },
    {
        "slug": "corporate-finance",
        "name": "Corporate, Banking & Insurance",
        "short": "Annual reports, branch collateral, forms, stationery and campaign print.",
        "icon": "bank",
        "title": "Corporate Printing for Banks & Listed Companies",
        "meta": "Annual reports, branch collateral, forms, stationery and signage for banks, insurers, telcos and listed companies in Sri Lanka. On schedule, confidential.",
        "h1": "Corporate Print for Banks, Insurance & Listed Companies",
        "intro": "Financial institutions and large corporates print at scale and on deadline: annual reports for the AGM, leaflets for every branch, application forms, statements, campaign posters and stationery for thousands of staff. We deliver all of it with the control and confidentiality your compliance team expects.",
        "pains": [
            "Annual report deadlines are fixed by the AGM and the CSE",
            "Hundreds of branches need identical print delivered on the same day",
            "Confidential documents require secure handling",
            "Procurement needs a vendor with documented quality and capacity",
        ],
        "solutions": [
            ("Annual & integrated reports", "Premium reports with dummy approval, shareholder mailing and registrar delivery.", "annual-reports-books"),
            ("Branch collateral", "Product leaflets, posters, standees and counter displays packed per branch.", "brochures-catalogues"),
            ("Forms & security print", "Application forms, NCR sets, numbered cheque-book covers and envelopes.", "business-stationery"),
            ("Stationery programmes", "Business cards and letterheads on demand across departments.", "business-stationery"),
            ("Campaign & signage", "Launch banners, branch signage, ATM and vehicle branding.", "large-format-signage"),
        ],
        "faqs": [
            ("Can you meet a fixed annual report deadline?", "Yes. We plan press slots backwards from your AGM date and provide a printed dummy for board sign-off."),
            ("Are you registered as a vendor with procurement systems?", "We complete vendor registration and provide company registration, tax and quality documentation on request."),
        ],
        "related_services": ["annual-reports-books", "brochures-catalogues", "business-stationery", "large-format-signage"],
    },
    {
        "slug": "education",
        "name": "Schools, Universities & Training",
        "short": "Prospectuses, certificates, exam papers, yearbooks, ID cards and exercise books.",
        "icon": "education",
        "title": "School & University Printing in Sri Lanka",
        "meta": "Prospectuses, yearbooks, certificates, secure exam papers, exercise books, ID cards and event banners for schools, universities and institutes.",
        "h1": "Print for Schools, Universities & Training Institutes",
        "intro": "Education runs on print. International schools, universities, tuition institutes and professional bodies rely on us for prospectuses that recruit, certificates that impress, exam papers that are secure, and yearbooks students keep for life.",
        "pains": [
            "Term-based deadlines: admissions season, exams, graduation, prize giving",
            "Confidential exam materials need secure printing",
            "Branding must be consistent from prospectus to school bag tag",
            "Budget-conscious purchasing with many small jobs",
        ],
        "solutions": [
            ("Prospectuses & brochures", "Recruitment brochures, course guides and open-day flyers.", "brochures-catalogues"),
            ("Certificates & awards", "Foil-stamped, embossed certificates with variable names and numbering.", "digital-printing"),
            ("Yearbooks & magazines", "Perfect-bound and hardcover yearbooks and school magazines.", "annual-reports-books"),
            ("Exam papers & exercise books", "Secure printing of question papers, answer booklets and branded exercise books.", "offset-printing"),
            ("ID cards & lanyards", "Student and staff cards, lanyards and visitor badges.", "business-stationery"),
            ("Event branding", "Graduation backdrops, sports-meet banners and wayfinding.", "large-format-signage"),
        ],
        "faqs": [
            ("Can you print exam papers securely?", "Yes. Exam jobs are printed in a restricted area with counted output and sealed packing."),
            ("Do you print certificates with student names?", "Yes. Send a spreadsheet and every certificate is printed with the correct name and number using variable data."),
        ],
        "related_services": ["brochures-catalogues", "digital-printing", "annual-reports-books", "business-stationery"],
    },
    {
        "slug": "real-estate-construction",
        "name": "Real Estate & Construction",
        "short": "Project brochures, hoardings, site signage, floor plans and sales-office print.",
        "icon": "building",
        "title": "Real Estate Brochures & Hoardings in Sri Lanka",
        "meta": "Project brochures, floor-plan booklets, construction hoardings, site signage and sales gallery displays for property developers in Sri Lanka.",
        "h1": "Print & Signage for Real Estate & Construction",
        "intro": "A property launch is a print-heavy campaign: brochures that justify the price, hoardings that dominate the street, and a sales gallery that closes the deal. We give developers, builders and architects one supplier for all of it.",
        "pains": [
            "Launch dates are fixed and marketing material must be ready together",
            "Hoardings and site signage must survive sun, rain and dust",
            "Premium brochures need premium paper and finishing",
            "Multiple projects need consistent yet distinct branding",
        ],
        "solutions": [
            ("Project brochures & floor plans", "Thick-stock brochures, folders and floor-plan booklets with foil and soft-touch finishes.", "brochures-catalogues"),
            ("Hoardings & site signage", "Full-colour hoardings, mesh banners, safety and wayfinding signs, installed.", "large-format-signage"),
            ("Sales gallery displays", "Backdrops, light boxes, acrylic displays and floor graphics.", "large-format-signage"),
            ("Corporate print", "Company profiles, tender documents and stationery.", "business-stationery"),
        ],
        "faqs": [
            ("Do you install hoardings at construction sites?", "Yes. We print, frame and install hoardings and safety signage island-wide."),
            ("What is the best finish for a luxury project brochure?", "Uncoated or soft-touch laminated 300 gsm cover with copper or gold foil and matt inner pages is the current favourite among developers."),
        ],
        "related_services": ["brochures-catalogues", "large-format-signage", "business-stationery", "offset-printing"],
    },
]

INDUSTRY_BY_SLUG = {i["slug"]: i for i in INDUSTRIES}
