"""Service pages – each entry becomes /services/<slug>/ with Service + FAQ schema."""

SERVICES = [
    {
        "slug": "packaging-boxes",
        "name": "Custom Printed Boxes & Folding Cartons",
        "short": "Folding cartons, product boxes and retail packaging printed to your dieline.",
        "icon": "box",
        "title": "Custom Printed Boxes & Folding Cartons | Sri Lanka",
        "meta": "Custom printed boxes and folding cartons made in Sri Lanka for tea, cosmetics, pharma and food brands. Free dieline and sample, 7–10 day turnaround.",
        "h1": "Custom Printed Boxes & Folding Cartons",
        "intro": "From a 50-piece launch run to 500,000 export cartons, we design, print, die-cut and glue folding cartons that sell your product on the shelf and survive the journey to it. Made in Colombo, shipped island-wide.",
        "keywords": ["custom printed boxes Sri Lanka", "folding carton manufacturer Sri Lanka", "product packaging boxes Colombo", "box printing Sri Lanka"],
        "sections": [
            {"h2": "Box styles we manufacture", "bullets": [
                "Straight tuck and reverse tuck end cartons (cosmetics, pharma, electronics)",
                "Crash-lock / auto-bottom cartons for heavier products and fast packing lines",
                "Sleeve and tray packaging for tea, chocolates and gift sets",
                "Window-patched boxes with clear PET or PLA film",
                "Display and counter-top boxes with tear-off fronts",
                "Hanging tab cartons for retail peg walls",
            ]},
            {"h2": "Materials and finishes", "p": "We stock 250–450 gsm folding box board (FBB/SBS), duplex board, kraft board and food-safe virgin board. Finishes include matt and gloss lamination, aqueous varnish, spot UV, hot foil stamping (gold, silver, holographic), embossing and debossing, soft-touch coating and water-based inks for food contact."},
            {"h2": "Why brands choose us for cartons", "bullets": [
                "Free structural design: we supply a dieline and a white physical sample before you commit",
                "Colour-managed offset printing with Pantone matching for brand consistency across reorders",
                "Export-ready: cartons packed flat, palletised and documented for sea or air freight",
                "Minimum order from 500 pcs on offset, from 50 pcs on digital for launches and test markets",
            ]},
        ],
        "specs": [("Minimum order", "50 pcs (digital) / 500 pcs (offset)"), ("Board", "250–450 gsm FBB, SBS, duplex, kraft"), ("Print", "Up to 6 colours + coating, Pantone matched"), ("Turnaround", "7–10 working days after artwork approval"), ("Sampling", "Free white sample, printed proof on request")],
        "ideal_for": ["Tea exporters", "Cosmetics & ayurveda", "Pharmaceuticals", "Food & confectionery", "Electronics & hardware"],
        "faqs": [
            ("What information do you need to quote a printed box?", "Product dimensions (or a sample of the product), quantity, board preference, number of print colours and finishes. If you have no dieline, we create one free of charge."),
            ("Can you produce food-grade boxes?", "Yes. We use virgin food-safe board and low-migration inks, and can supply a material declaration for your export documentation."),
            ("How long does a first order take?", "Dieline and white sample in 2–3 days, printed proof in 3–4 days, then 7–10 working days for production. Repeat orders are faster because the tooling already exists."),
        ],
        "related_services": ["rigid-gift-boxes", "labels-stickers", "design-prepress", "corrugated-boxes"],
        "related_industries": ["tea-exporters", "cosmetics-ayurveda", "pharmaceutical-healthcare", "food-beverage"],
    },
    {
        "slug": "corrugated-boxes",
        "name": "Corrugated Boxes & Shipping Cartons",
        "short": "Printed shipping cartons, mailer boxes and export-grade corrugated packaging.",
        "icon": "shipping",
        "title": "Corrugated Boxes & Shipping Cartons | Sri Lanka",
        "meta": "Corrugated boxes, printed shipping cartons and e-commerce mailer boxes made in Sri Lanka. 3 and 5 ply, ECT tested, bulk pricing. Request a quote.",
        "h1": "Corrugated Boxes & Shipping Cartons",
        "intro": "Strong, print-ready corrugated packaging for exporters, e-commerce sellers and factories. Regular slotted cartons, die-cut mailers and custom inserts in 3-ply and 5-ply board, flexo or litho-laminated printing.",
        "keywords": ["corrugated boxes Sri Lanka", "shipping cartons Sri Lanka", "mailer boxes Sri Lanka", "e-commerce packaging Sri Lanka", "export cartons Colombo"],
        "sections": [
            {"h2": "Corrugated products", "bullets": [
                "Regular slotted cartons (RSC) for export and distribution",
                "Die-cut mailer boxes with tuck-in lids for e-commerce and subscription boxes",
                "Litho-laminated display cartons with full-colour graphics",
                "Partitions, inserts and pads for glass, ceramics and electronics",
                "Heavy-duty double-wall cartons for machinery and furniture",
                "Pizza boxes, bakery boxes and takeaway boxes in E-flute",
            ]},
            {"h2": "Board grades and testing", "p": "We produce B, C, E and BC flute board with kraft, white-top kraft or test liner facings. Every export specification is tested for bursting strength, edge crush (ECT) and box compression (BCT) so your cartons meet buyer and freight-forwarder requirements."},
            {"h2": "Printing options", "p": "Choose 1–4 colour flexographic printing for cost-effective shipper cartons, or litho-lamination for premium retail-ready packaging with photographic quality. Both include brand colour matching and barcode verification."},
        ],
        "specs": [("Minimum order", "100 pcs (die-cut mailers) / 500 pcs (RSC)"), ("Board", "3-ply and 5-ply, B/C/E/BC flute"), ("Print", "Flexo 1–4 colours or litho-laminated CMYK"), ("Turnaround", "5–10 working days"), ("Testing", "ECT, BCT, bursting strength reports available")],
        "ideal_for": ["Exporters", "E-commerce & D2C brands", "Apparel factories", "Food processors", "Furniture & appliances"],
        "faqs": [
            ("What is the difference between 3-ply and 5-ply?", "3-ply (single wall) has one fluted layer and suits products up to about 10–15 kg. 5-ply (double wall) has two fluted layers for heavy or stacked export loads."),
            ("Do you make small quantities of mailer boxes?", "Yes. Die-cut mailer boxes start from 100 pieces, which makes them practical for Instagram brands and subscription boxes."),
            ("Can you print inside the box?", "Yes. Inside printing on mailer boxes is a popular unboxing-experience feature for D2C brands."),
        ],
        "related_services": ["packaging-boxes", "labels-stickers", "paper-bags", "design-prepress"],
        "related_industries": ["ecommerce-retail", "apparel-garment", "food-beverage", "tea-exporters"],
    },
    {
        "slug": "labels-stickers",
        "name": "Label & Sticker Printing",
        "short": "Roll labels, product stickers, barcode labels and shrink sleeves.",
        "icon": "label",
        "title": "Label & Sticker Printing in Sri Lanka | Roll Labels",
        "meta": "Roll labels, product stickers, barcode and waterproof labels and shrink sleeves printed in Sri Lanka. Digital from 250 pcs, flexo for volume. Get a quote.",
        "h1": "Label & Sticker Printing",
        "intro": "Self-adhesive labels that stay on and stay sharp: roll labels for filling lines, sheet labels for hand application, waterproof labels for bottles and jars, and variable-data barcode labels for exporters.",
        "keywords": ["label printing Sri Lanka", "sticker printing Colombo", "roll labels Sri Lanka", "product labels Sri Lanka", "waterproof labels Sri Lanka"],
        "sections": [
            {"h2": "Label types", "bullets": [
                "Roll labels on 76 mm or 40 mm cores for automatic and semi-automatic applicators",
                "Paper, PP, PET, BOPP and clear 'no-label look' materials",
                "Waterproof and oil-resistant labels for cosmetics, beverages, oils and chemicals",
                "Freezer-grade and removable adhesives",
                "Barcode, batch and expiry variable-data labels",
                "Shrink sleeves and wrap-around labels for bottles and cans",
                "Die-cut stickers, kiss-cut sticker sheets and branded packing tape",
            ]},
            {"h2": "Print technology", "p": "Digital label printing gives you photographic quality with no plate cost, ideal for short runs, many SKUs and seasonal designs. For high-volume lines we use flexographic printing with UV inks, cold foil and spot varnish at lower unit cost."},
            {"h2": "Compliance made easy", "p": "We help you fit Sri Lanka Standards Institution (SLS) marks, nutrition panels, halal and organic logos, barcodes and multi-language text on the label without compromising design, and we verify barcodes before dispatch."},
        ],
        "specs": [("Minimum order", "250 labels (digital)"), ("Materials", "Paper, PP, PET, BOPP, clear, kraft, foil"), ("Finish", "Matt/gloss lamination, UV varnish, foil, embossing"), ("Turnaround", "3–5 working days digital, 7–10 flexo"), ("Delivery", "Rolls, sheets or fan-folded")],
        "ideal_for": ["Food & beverage", "Cosmetics & ayurveda", "Spice & coconut exporters", "Pharmaceuticals", "Home & craft brands"],
        "faqs": [
            ("Which label material should I use for bottles that get wet?", "Choose PP or PET synthetic labels with a permanent adhesive and a laminated or UV-varnished surface. They resist water, oil and rubbing."),
            ("Can you print different flavours or SKUs in one order?", "Yes. Digital printing lets you split one order across many designs with no extra plate charges."),
            ("Do you supply labels for automatic applicators?", "Yes. Tell us the core size, roll direction (unwind position) and maximum roll diameter and we will match your machine."),
        ],
        "related_services": ["packaging-boxes", "digital-printing", "design-prepress", "food-packaging"],
        "related_industries": ["food-beverage", "cosmetics-ayurveda", "pharmaceutical-healthcare", "tea-exporters"],
    },
    {
        "slug": "rigid-gift-boxes",
        "name": "Rigid & Luxury Gift Boxes",
        "short": "Premium set-up boxes, magnetic closure boxes and gift packaging.",
        "icon": "gift",
        "title": "Rigid & Luxury Gift Boxes Made in Sri Lanka",
        "meta": "Magnetic closure, lid-and-base and drawer boxes for tea, jewellery, cosmetics and corporate gifts. Foil, embossing and fitted inserts. From 100 pieces.",
        "h1": "Rigid & Luxury Gift Boxes",
        "intro": "Hand-finished rigid boxes for products that deserve an unboxing moment: premium teas, jewellery, gems, corporate gifts, cosmetics and wedding favours. Greyboard cores wrapped in printed or textured papers with foil, embossing and fitted inserts.",
        "keywords": ["rigid boxes Sri Lanka", "luxury gift boxes Sri Lanka", "magnetic gift box Colombo", "tea gift box packaging Sri Lanka", "jewellery box manufacturer Sri Lanka"],
        "sections": [
            {"h2": "Rigid box styles", "bullets": [
                "Magnetic closure (collapsible or pre-glued) boxes",
                "Lid and base (shoulder-neck) boxes",
                "Drawer / slide boxes and book-style boxes",
                "Round and hexagonal tubes for teas and candles",
                "Hamper and presentation trays for corporate gifting",
            ]},
            {"h2": "Inserts and finishing", "p": "EVA foam, moulded pulp, satin-lined board and die-cut cardboard inserts hold products securely. Finishing options include hot foil, blind embossing, spot UV, soft-touch lamination, ribbon pulls and custom tissue paper."},
            {"h2": "Small runs welcome", "p": "Because rigid boxes are assembled by hand, we can produce as few as 100 pieces for a product launch, a wedding or an executive gifting programme, and scale to tens of thousands for seasonal retail."},
        ],
        "specs": [("Minimum order", "100 pcs"), ("Core", "1.5–3 mm greyboard"), ("Wrap", "Printed art paper, textured / speciality papers, cloth"), ("Turnaround", "10–15 working days"), ("Sampling", "Physical pre-production sample")],
        "ideal_for": ["Tea & gift brands", "Jewellery & gems", "Corporate gifting", "Cosmetics", "Weddings & events"],
        "faqs": [
            ("Are rigid boxes shipped assembled?", "Standard rigid boxes ship assembled. For export volume we offer collapsible magnetic boxes that ship flat and save up to 70% on freight."),
            ("Can you match a Pantone colour on textured paper?", "Yes, within the tolerance of the paper. We always supply a physical sample for approval before production."),
        ],
        "related_services": ["packaging-boxes", "paper-bags", "design-prepress", "brochures-catalogues"],
        "related_industries": ["tea-exporters", "cosmetics-ayurveda", "corporate-finance", "hotels-hospitality"],
    },
    {
        "slug": "offset-printing",
        "name": "Offset Printing",
        "short": "High-volume, colour-accurate sheet-fed offset for brochures, packaging and books.",
        "icon": "press",
        "title": "Offset Printing in Colombo, Sri Lanka",
        "meta": "Commercial offset printing in Colombo: brochures, catalogues, annual reports, packaging and books on 4 and 5 colour presses with Pantone matching.",
        "h1": "Offset Printing",
        "intro": "Our sheet-fed offset presses deliver the colour accuracy and low unit cost that high-volume marketing print and packaging demand. If you need 1,000 or more of anything, offset is usually the answer.",
        "keywords": ["offset printing Sri Lanka", "commercial printing Colombo", "printing press Sri Lanka", "bulk printing Sri Lanka"],
        "sections": [
            {"h2": "What we print offset", "bullets": [
                "Brochures, flyers, leaflets and catalogues",
                "Annual reports, magazines and books",
                "Folding cartons and litho-laminated packaging",
                "Posters, calendars and diaries",
                "Letterheads, envelopes, NCR forms and stationery",
            ]},
            {"h2": "Colour you can trust", "p": "Computer-to-plate (CTP) prepress, ISO-based colour management, G7-style calibration and Pantone spot colours mean your brand blue is the same on the brochure, the box and the label, on every reorder."},
            {"h2": "Paper and finishing", "p": "Art paper and board from 80 to 400 gsm, uncoated and recycled stocks, and speciality papers on request. In-house finishing includes lamination, UV, foil, die-cutting, folding, saddle stitching, perfect binding and wire-o."},
        ],
        "specs": [("Presses", "4 and 5 colour sheet-fed, up to B1"), ("Minimum order", "500 pcs (1,000+ recommended)"), ("Stock", "80–400 gsm coated, uncoated, board"), ("Turnaround", "5–7 working days"), ("Proofing", "Digital colour proof, press proof on request")],
        "ideal_for": ["Corporate & finance", "FMCG brands", "Publishers", "Advertising agencies", "Education"],
        "faqs": [
            ("Offset or digital: which is cheaper?", "Digital is cheaper below roughly 500–1,000 copies because there are no plates. Above that, offset's lower cost per sheet wins. We quote both when the quantity is borderline."),
            ("Can you handle agency artwork in InDesign or Illustrator?", "Yes. We accept press-ready PDF/X-4 files and packaged InDesign or Illustrator files with fonts and links, and we run a free preflight before printing."),
        ],
        "related_services": ["brochures-catalogues", "annual-reports-books", "packaging-boxes", "business-stationery"],
        "related_industries": ["corporate-finance", "education", "real-estate-construction", "hotels-hospitality"],
    },
    {
        "slug": "digital-printing",
        "name": "Digital Printing",
        "short": "Short-run, fast-turnaround printing with variable data and no plate costs.",
        "icon": "digital",
        "title": "Digital Printing Colombo | Short-Run, 24–72 Hours",
        "meta": "Fast digital printing in Colombo: short-run brochures, business cards, labels, boxes, certificates and event print in 24–72 hours. Get a quote today.",
        "h1": "Digital Printing",
        "intro": "When you need it this week, in small quantities, or personalised for every recipient, our production digital presses print offset-quality colour on paper, board, labels and synthetics with 24–72 hour turnaround.",
        "keywords": ["digital printing Colombo", "short run printing Sri Lanka", "same day printing Colombo", "fast printing Sri Lanka"],
        "sections": [
            {"h2": "Ideal digital jobs", "bullets": [
                "Business cards, flyers and brochures from 50 copies",
                "Product boxes and labels for launches and test markets",
                "Personalised direct mail, certificates and name badges",
                "Menus, table talkers and event print",
                "Proposal documents, training manuals and booklets",
            ]},
            {"h2": "Variable data printing", "p": "Print names, codes, QR codes, serial numbers or regional pricing that change on every piece, all in one run. Ideal for loyalty cards, invitations, vouchers, exam certificates and traceable product labels."},
            {"h2": "Same finishes as offset", "p": "Digital jobs get the same in-house finishing: lamination, spot UV, foil, die-cutting, creasing, folding and binding, so a 100-piece launch box looks identical to the 10,000-piece reorder printed offset later."},
        ],
        "specs": [("Minimum order", "1 pc"), ("Sheet size", "Up to SRA3+ (330 × 488 mm), banner sheets to 1.2 m"), ("Stock", "80–400 gsm, synthetics, textured papers"), ("Turnaround", "24–72 hours"), ("Data", "Variable data from Excel/CSV")],
        "ideal_for": ["Start-ups & SMEs", "Event & wedding planners", "Agencies", "Education", "Hospitality"],
        "faqs": [
            ("How fast can you print business cards in Colombo?", "Standard business cards are ready in 24 hours after artwork approval; laminated or foiled cards in 48–72 hours."),
            ("Will digital colour match my offset brochures?", "Our digital presses are calibrated to the same colour targets as the offset presses, so brand colours match closely. For critical Pantone colours we advise a printed proof."),
        ],
        "related_services": ["business-stationery", "labels-stickers", "brochures-catalogues", "large-format-signage"],
        "related_industries": ["ecommerce-retail", "education", "hotels-hospitality", "corporate-finance"],
    },
    {
        "slug": "brochures-catalogues",
        "name": "Brochures, Catalogues & Marketing Print",
        "short": "Flyers, brochures, catalogues, folders and point-of-sale material.",
        "icon": "brochure",
        "title": "Brochure & Catalogue Printing in Sri Lanka",
        "meta": "Flyers, tri-fold brochures, product catalogues, presentation folders, posters and point-of-sale displays printed in Sri Lanka with premium finishes.",
        "h1": "Brochures, Catalogues & Marketing Print",
        "intro": "Marketing print that earns its place on the desk: brochures, product catalogues, presentation folders, posters, shelf talkers and point-of-sale displays, planned with your campaign timeline in mind.",
        "keywords": ["brochure printing Sri Lanka", "catalogue printing Colombo", "flyer printing Sri Lanka", "presentation folder printing Sri Lanka"],
        "sections": [
            {"h2": "Marketing print we produce", "bullets": [
                "Flyers and leaflets (A6 to A3, single or double sided)",
                "Bi-fold, tri-fold, z-fold and gate-fold brochures",
                "Product catalogues and lookbooks, saddle-stitched or perfect bound",
                "Presentation folders with business card slits and pockets",
                "Posters, danglers, shelf talkers, wobblers and standees",
                "Calendars, diaries, notebooks and corporate gifts",
            ]},
            {"h2": "Finishes that get noticed", "p": "Soft-touch lamination, spot UV over matt, gold and copper foil, embossed logos, die-cut shapes and textured stocks turn a standard brochure into a keepsake. We show you physical swatches before you decide."},
            {"h2": "Campaign-ready logistics", "p": "We can pack brochures per branch, per sales rep or per event, label the cartons and deliver island-wide, so your campaign launches on the same day everywhere."},
        ],
        "specs": [("Minimum order", "50 (digital) / 500 (offset)"), ("Stock", "130–350 gsm art, uncoated, recycled"), ("Finish", "Lamination, spot UV, foil, embossing, die-cut"), ("Turnaround", "3–7 working days"), ("Extras", "Branch-wise packing and distribution")],
        "ideal_for": ["Real estate developers", "Banks & insurance", "Hotels & tourism", "Retail chains", "Education"],
        "faqs": [
            ("What paper is best for a brochure?", "170 gsm art paper is the popular choice for folded brochures. Use 250–300 gsm for single-sheet flyers that must feel premium, and 300–350 gsm for folders."),
            ("Can you design the brochure too?", "Yes. Our in-house design team creates brochures, catalogues and packaging artwork, or prepares your agency's files for press."),
        ],
        "related_services": ["offset-printing", "digital-printing", "annual-reports-books", "large-format-signage"],
        "related_industries": ["real-estate-construction", "corporate-finance", "hotels-hospitality", "education"],
    },
    {
        "slug": "business-stationery",
        "name": "Business Cards & Corporate Stationery",
        "short": "Business cards, letterheads, envelopes, NCR forms and branded stationery.",
        "icon": "card",
        "title": "Business Cards & Letterhead Printing, Colombo",
        "meta": "Business cards in 24 hours, letterheads, envelopes, NCR invoice books and branded stationery printed in Colombo. Foil, spot UV and embossed finishes.",
        "h1": "Business Cards & Corporate Stationery",
        "intro": "Everything a business puts its name on: cards that make an impression, letterheads and envelopes that match, and the invoice books, delivery notes and forms that keep operations running.",
        "keywords": ["business card printing Colombo", "letterhead printing Sri Lanka", "NCR invoice book printing Sri Lanka", "corporate stationery Sri Lanka"],
        "sections": [
            {"h2": "Stationery range", "bullets": [
                "Business cards: standard, laminated, spot UV, foil, embossed, rounded corners, 600 gsm layered",
                "Letterheads, compliment slips, envelopes (window and plain)",
                "NCR duplicate/triplicate invoice books, receipt books, delivery notes, job cards",
                "ID cards, lanyards and name badges",
                "Notebooks, notepads and diaries with your branding",
                "Certificates, folders and presentation covers",
            ]},
            {"h2": "Corporate stationery programmes", "p": "For companies with many branches we hold your templates, print on demand per branch and deliver directly, with consolidated monthly invoicing. One supplier, one standard, every branch."},
        ],
        "specs": [("Business cards", "From 100 pcs, 24-hour standard turnaround"), ("Letterheads", "100 gsm bond or 120 gsm laid/linen"), ("NCR books", "50 or 100 sets, numbered, perforated"), ("Turnaround", "1–5 working days"), ("Branch programmes", "Template library + scheduled reprints")],
        "ideal_for": ["Companies of all sizes", "Banks & finance", "Law & accounting firms", "Start-ups", "Hospitals & clinics"],
        "faqs": [
            ("Can I order business cards for several staff in one go?", "Yes. Send us a spreadsheet of names and titles and we print every card from one template with variable data."),
            ("Do you print numbered invoice books with company registration details?", "Yes. NCR books are printed with sequential numbering, perforation and your legal details, in duplicate or triplicate."),
        ],
        "related_services": ["digital-printing", "brochures-catalogues", "offset-printing", "design-prepress"],
        "related_industries": ["corporate-finance", "education", "pharmaceutical-healthcare", "real-estate-construction"],
    },
    {
        "slug": "large-format-signage",
        "name": "Large Format Printing & Signage",
        "short": "Banners, hoardings, backdrops, roll-ups, vehicle graphics and shop signage.",
        "icon": "banner",
        "title": "Large Format Printing & Signage in Sri Lanka",
        "meta": "Banners, hoardings, roll-up standees, exhibition backdrops, shop signage, vehicle branding and window graphics printed and installed across Sri Lanka.",
        "h1": "Large Format Printing & Signage",
        "intro": "From a single roll-up banner to a 30-metre construction hoarding, we print and install signage that keeps your brand visible on the street, at the exhibition and in the store.",
        "keywords": ["large format printing Sri Lanka", "banner printing Colombo", "hoarding printing Sri Lanka", "roll up banner Sri Lanka", "signage company Colombo"],
        "sections": [
            {"h2": "Large format products", "bullets": [
                "Flex and vinyl banners, mesh banners for scaffolding",
                "Roll-up and X standees, pop-up backdrops and media walls",
                "Construction hoardings and project-site signage",
                "Shop-front signage, light boxes and 3D letters",
                "Vehicle wraps and delivery-van graphics",
                "Wall murals, floor graphics, window decals and one-way vision film",
                "Foam board, sunboard and acrylic point-of-sale displays",
            ]},
            {"h2": "Outdoor-ready materials", "p": "UV-resistant eco-solvent and UV-cured inks, laminated for the Sri Lankan sun and monsoon. We advise on the right material for every location and provide installation teams for Colombo and major cities."},
        ],
        "specs": [("Print width", "Up to 3.2 m seamless"), ("Materials", "Flex, vinyl, mesh, canvas, foam board, acrylic, ACP"), ("Turnaround", "24–72 hours"), ("Installation", "Available island-wide"), ("Minimum order", "1 pc")],
        "ideal_for": ["Real estate & construction", "Retail & showrooms", "Event & exhibition organisers", "Hotels", "Banks & telcos"],
        "faqs": [
            ("How long do outdoor banners last?", "Laminated vinyl banners last 2–3 years outdoors. Standard flex banners suit short campaigns of 3–6 months."),
            ("Do you install hoardings outside Colombo?", "Yes. Our installation teams cover the Western Province and travel island-wide for larger projects."),
        ],
        "related_services": ["digital-printing", "brochures-catalogues", "business-stationery", "design-prepress"],
        "related_industries": ["real-estate-construction", "ecommerce-retail", "hotels-hospitality", "corporate-finance"],
    },
    {
        "slug": "paper-bags",
        "name": "Printed Paper Bags",
        "short": "Kraft and art-paper carry bags with twisted or ribbon handles.",
        "icon": "bag",
        "title": "Printed Paper Bags Manufacturer in Sri Lanka",
        "meta": "Custom printed kraft and laminated paper bags with twisted or ribbon handles, made in Sri Lanka for retail, bakeries and hotels. From 500 pieces.",
        "h1": "Printed Paper Bags",
        "intro": "With single-use plastic restrictions tightening in Sri Lanka, printed paper bags are the retail standard. We manufacture kraft, white kraft and laminated art-paper bags in every size, with handles to match your brand.",
        "keywords": ["paper bags Sri Lanka", "printed paper bags Colombo", "kraft paper bags manufacturer Sri Lanka", "shopping bags printing Sri Lanka"],
        "sections": [
            {"h2": "Bag styles", "bullets": [
                "Brown and white kraft bags with twisted paper handles",
                "Laminated art-paper bags with ribbon, rope or die-cut handles",
                "Flat-bottom bakery and food bags, greaseproof options",
                "Wine bags, gift bags and boutique bags",
                "Takeaway bags with reinforced bottoms for restaurants",
            ]},
            {"h2": "Sustainable by default", "p": "FSC-certified papers, water-based inks and no plastic lamination on request. We can print a recycled-content statement and your sustainability message on every bag."},
        ],
        "specs": [("Minimum order", "500 pcs"), ("Paper", "90–150 gsm kraft, 157–250 gsm art paper"), ("Print", "1–4 colour flexo or full-colour offset"), ("Handles", "Twisted paper, ribbon, cotton rope, die-cut"), ("Turnaround", "7–12 working days")],
        "ideal_for": ["Retail & fashion", "Bakeries & cafés", "Hotels & resorts", "Pharmacies", "Events"],
        "faqs": [
            ("What size paper bag should I order?", "Tell us the largest product it will carry and we will recommend sizes from our standard range or make a custom size at no extra cost."),
            ("Are your paper bags food safe?", "Yes. We offer virgin kraft and greaseproof-lined bags with food-grade inks for bakeries and restaurants."),
        ],
        "related_services": ["food-packaging", "rigid-gift-boxes", "labels-stickers", "packaging-boxes"],
        "related_industries": ["ecommerce-retail", "hotels-hospitality", "food-beverage", "pharmaceutical-healthcare"],
    },
    {
        "slug": "food-packaging",
        "name": "Food Packaging & Takeaway Boxes",
        "short": "Cake boxes, burger boxes, pizza boxes, cups, sleeves and food-grade wraps.",
        "icon": "food",
        "title": "Food Packaging & Takeaway Box Printing, Sri Lanka",
        "meta": "Printed cake boxes, burger and pizza boxes, meal boxes, paper cups and sleeves on food-grade board with low-migration inks. Made in Sri Lanka.",
        "h1": "Food Packaging & Takeaway Boxes",
        "intro": "Packaging that keeps food fresh and photographs well on delivery apps. Food-grade board, grease-resistant coatings and designs that fit your kitchen workflow, for bakeries, cloud kitchens, restaurants and food brands.",
        "keywords": ["food packaging Sri Lanka", "cake box printing Sri Lanka", "takeaway box printing Colombo", "paper cups printing Sri Lanka", "burger box Sri Lanka"],
        "sections": [
            {"h2": "Food packaging range", "bullets": [
                "Cake boxes, cupcake boxes with inserts, pastry and doughnut boxes",
                "Burger boxes, fries cartons, hot-dog trays, sandwich wedges",
                "Pizza boxes in E-flute, meal-prep and biriyani boxes",
                "Single and double-wall paper cups, cup sleeves, lids",
                "Greaseproof wrapping paper, tray liners and sachets",
                "Chocolate boxes, confectionery sleeves and snack cartons",
            ]},
            {"h2": "Built for delivery", "p": "Tamper-evident closures, vent holes that stop sogginess, stackable designs and space for delivery-app stickers. We test with your actual products before a full run."},
        ],
        "specs": [("Minimum order", "500 pcs (250 for cake boxes)"), ("Board", "Food-grade FBB, kraft, PE/PLA-coated, E-flute"), ("Inks", "Low-migration, water-based"), ("Turnaround", "7–10 working days"), ("Samples", "Free structural sample for fit testing")],
        "ideal_for": ["Bakeries & cake studios", "Cloud kitchens", "Restaurants & QSR", "Coffee shops", "Confectionery brands"],
        "faqs": [
            ("Are the boxes safe for direct food contact?", "Yes. We use food-grade virgin board and low-migration inks, with PE or compostable PLA coating where a moisture barrier is needed."),
            ("Can I get small quantities for a new bakery?", "Yes. Cake boxes start at 250 pieces and can be printed digitally so a new business can start with a branded box from day one."),
        ],
        "related_services": ["paper-bags", "labels-stickers", "packaging-boxes", "corrugated-boxes"],
        "related_industries": ["food-beverage", "hotels-hospitality", "ecommerce-retail"],
    },
    {
        "slug": "annual-reports-books",
        "name": "Annual Reports, Books & Publications",
        "short": "Annual reports, magazines, books, manuals and yearbooks with every binding style.",
        "icon": "book",
        "title": "Annual Report & Book Printing in Sri Lanka",
        "meta": "Annual reports, magazines, textbooks, yearbooks and manuals printed in Sri Lanka with saddle stitch, PUR, case and wire-o binding. Deadline driven.",
        "h1": "Annual Reports, Books & Publications",
        "intro": "Deadline-driven publication printing for listed companies, publishers, schools and institutions: annual reports, magazines, textbooks, yearbooks, training manuals and coffee-table books, with binding to suit.",
        "keywords": ["annual report printing Sri Lanka", "book printing Sri Lanka", "magazine printing Colombo", "yearbook printing Sri Lanka", "perfect binding Sri Lanka"],
        "sections": [
            {"h2": "Publications we print", "bullets": [
                "Annual and integrated reports for CSE-listed companies and banks",
                "Magazines, journals and newsletters",
                "Textbooks, exercise books and past-paper collections",
                "Yearbooks, prospectuses and school magazines",
                "Coffee-table books, photo books and catalogues",
                "Training manuals, SOP binders and technical documentation",
            ]},
            {"h2": "Binding options", "p": "Saddle stitching for up to about 80 pages, perfect (PUR) binding for lay-flat durability, section-sewn hardcover case binding for books that last, and wire-o or spiral binding for manuals that need to lie open."},
            {"h2": "Annual report season, handled", "p": "We schedule press time around AGM dates, accept late financial pages, print a bound dummy for board sign-off and can deliver directly to the registrar or courier to shareholders."},
        ],
        "specs": [("Minimum order", "50 (digital) / 300 (offset)"), ("Binding", "Saddle stitch, PUR, sewn case bound, wire-o"), ("Stock", "70–170 gsm text, 250–350 gsm covers"), ("Turnaround", "5–15 working days depending on binding"), ("Extras", "Dummy copies, CD/USB inserts, shareholder mailing")],
        "ideal_for": ["Listed companies & banks", "Schools & universities", "Publishers", "NGOs & institutions", "Government bodies"],
        "faqs": [
            ("How many pages can be saddle stitched?", "Up to about 80 pages on 100 gsm paper. Beyond that we recommend perfect binding."),
            ("Can you print a small number of hardcover books?", "Yes. Digital printing with case binding lets us produce from 50 copies, useful for commemorative books and family histories."),
        ],
        "related_services": ["offset-printing", "digital-printing", "brochures-catalogues", "design-prepress"],
        "related_industries": ["corporate-finance", "education", "real-estate-construction"],
    },
    {
        "slug": "design-prepress",
        "name": "Packaging Design & Prepress",
        "short": "Structural design, dielines, artwork, proofing and print-ready file preparation.",
        "icon": "design",
        "title": "Packaging Design & Prepress Services, Sri Lanka",
        "meta": "Structural packaging design, free dielines, artwork adaptation, 3D mock-ups and colour proofing in Sri Lanka. Free preflight on every print job.",
        "h1": "Packaging Design & Prepress",
        "intro": "Great print starts before the press. Our structural designers and prepress team create dielines, adapt artwork, build 3D mock-ups and check every file so that what you approve on screen is what comes off the machine.",
        "keywords": ["packaging design Sri Lanka", "dieline design Colombo", "prepress services Sri Lanka", "label design Sri Lanka"],
        "sections": [
            {"h2": "Design services", "bullets": [
                "Structural packaging design and dielines (ECMA/FEFCO styles and custom)",
                "Packaging and label artwork, brand adaptation across SKUs",
                "3D renders and physical white samples",
                "Brochure, catalogue and annual report layout",
                "Regulatory artwork: nutrition panels, barcodes, multi-language",
            ]},
            {"h2": "Prepress and proofing", "p": "Free preflight on every job checks bleed, resolution, fonts, overprint and colour mode. Digital colour-managed proofs or press proofs let you approve with confidence, and we archive your files for effortless reorders."},
        ],
        "specs": [("Dielines", "Free with any packaging order"), ("Files", "PDF/X-4, AI, INDD, PSD accepted"), ("Proofs", "Soft proof, contract colour proof, press proof"), ("Turnaround", "Dieline 1–2 days, artwork 3–5 days"), ("Archive", "Files stored for reorders")],
        "ideal_for": ["Brands launching products", "Exporters", "Agencies", "Start-ups", "Food & cosmetics"],
        "faqs": [
            ("I only have a logo. Can you design my packaging?", "Yes. We start from your product, target market and brand guidelines, propose structures and artwork, and provide a physical sample before print."),
            ("What is a dieline?", "A dieline is the flat template showing cut, crease and glue lines of a box or label. Artwork is placed on it so that it prints and folds correctly."),
        ],
        "related_services": ["packaging-boxes", "labels-stickers", "rigid-gift-boxes", "brochures-catalogues"],
        "related_industries": ["cosmetics-ayurveda", "food-beverage", "tea-exporters", "ecommerce-retail"],
    },
]

SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}
